# -*- coding: UTF-8 -*-

VIEW_NOTIFY_APP_CLOSE_DATA = 'view_notify_app_close_data'
VIEW_NOTIFY_EXCEPTION_DATA = 'view_notify_exception_data'
VIEW_NOTIFY_TRY_LOGIN_DATA = 'view_notify_try_login_data'
VIEW_NOTIFY_ADD_IMAGE_DATA = 'view_notify_add_image_data'
VIEW_NOTIFY_ENTER_EXEC_DATA = 'view_notify_enter_exec_data'
VIEW_NOTIFY_START_EXEC_DATA = 'view_notify_start_exec_data'
VIEW_NOTIFY_STOP_EXEC_DATA = 'view_notify_stop_exec_data'
VIEW_NOTIFY_UPDATE_SETTINGS_DATA = 'view_notify_update_settings_data'

VIEW_QUERY_TITLE_ICO_DATA = 'view_query_app_title_data'
VIEW_QUERY_ENV_DEFINE_DATA = 'view_query_env_define_data'
VIEW_QUERY_LOGIN_LIMIT_DATA = 'view_query_login_limit_data'
VIEW_QUERY_ABOUT_INFO_DATA = 'view_query_app_about_data'
VIEW_QUERY_PHOTO_IMAGE_DATA = 'view_query_photo_image_data'
VIEW_QUERY_PREFERENCE_IP_DATA = 'view_query_preference_ip_data'
VIEW_QUERY_DEFAULT_PWD_DATA = 'view_query_default_pwd_data'
VIEW_QUERY_TREE_VIEW_DATA = 'view_query_tree_view_data'
VIEW_QUERY_WIDGETS_DATA = 'view_query_widgets_data'
VIEW_QUERY_RUNNING_TASK_DATA = 'view_query_running_task_data'
VIEW_QUERY_IPS_STATE_DATA = 'view_query_ip_state_data'
VIEW_QUERY_SERVER_CACHE_DATA = 'view_query_server_cache_data'
VIEW_QUERY_SETTINGS_DATA = 'view_query_settings_data'

MODEL_NOTIFY_APP_TITLE_DATA = 'model_notify_app_title_data'
MODEL_NOTIFY_APP_TREES_DATA = 'model_notify_app_trees_data'
MODEL_NOTIFY_APP_WIDGETS_DATA = 'model_notify_app_widgets_data'
MODEL_NOTIFY_EXCEPTION_DATA = 'model_notify_exception_data'
MODEL_NOTIFY_LOGIN_RETURN_DATA = 'model_notify_login_result_data'
MODEL_NOTIFY_LOGIN_STATE_DATA = 'model_notify_login_state_data'
MODEL_NOTIFY_INSERT_TEXT_DATA = 'model_notify_insert_text_data'
MODEL_NOTIFY_ENTER_EXEC_RESULT_DATA = 'model_notify_enter_exec_result_data'
MODEL_NOTIFY_START_EXEC_RESULT_DATA = 'model_notify_start_exec_result_data'
MODEL_NOTIFY_DELAY_LOOP_TIMER_DATA = 'model_notify_delay_loop_timer_data'